config/routes.rb
Rails.application.routes.draw do

  post 'search' => 'pages#search'

  root 'pages#home'

  get 'messages.js' => 'messages#index'

  get 'signup' => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users do
    resources :characters
  end

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :universes do
    resources :groups do
      resources :rooms
    end
  end

  resources :rooms do
    resources :messages, only: [:create]
    resources :participants
  end

  resources :tags, only: [:index, :show]

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :room
  belongs_to :speaker, polymorphic: true
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :logged_in_user, only: [:create]

  def index
    @messages = Message.where("room_id = ? and created_at > ?", params[:room_id], Time.at(params[:after].to_i + 1))
  end

  def create
    start = 1.second.ago
    @room = Room.find_by_id(params[:room_id])
    @message = @room.messages.build(message_params)
    if params[:message][:speaker_type] == 'User'
      @message.speaker = current_user
    else
      @message.speaker = Character.find_by_id(params[:message][:speaker_id])
    end

    unless @room.group.users.exists?(current_user.id)
      Member.create(level:'New', user:current_user, group:@room.group)
    end

    unless @message.save
      flash[:danger] = 'Unable to submit message'
      redirect_to @room
    end

    @messages = @room.messages.where("created_at > ?", Time.at(start))
    @clear = params[:message][:speaker_type] == 'User' ? 'new_message_ooc' : 'new_message_char'

    respond_to do |format|
      format.html { redirect_to @room }
      format.js
    end
  end

  private

    def message_params
      params.require(:message).permit(:content, :speaker_type, :speaker_id)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_message.html.erb
<% unless message.content.blank? %>
    <div class="message" data-time="<%= message.created_at.to_i %>">
      <% if message.speaker_id.present? %>
          <% if message.speaker_type == 'User' %>
              <div class="user_message">
                <%= render User.find(message.speaker_id) %>
                <%= render html: message.content.bbcode_to_html.html_safe %>
              </div>
          <% else %>
              <div class="character_message">
                <%= render Character.find(message.speaker_id) %>
                <%= render html: message.content.bbcode_to_html.html_safe %>
              </div>
          <% end %>
      <% end %>
    </div>
<% end %>

app/views/messages/_message_form_character.html.erb
<%= form_for [@room, @message], remote: true, html: {id:"new_message_char"} do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
    <%= f.hidden_field :speaker_type, :value => 'Character' %>
    <aside class="char_select_contain"><%= f.select :speaker_id, @participants.where(user_id: current_user).map {|o| [ o.avatar.present? ? '' : o.name, o.id, title: o.avatar.present? ? o.avatar.url(:icon) : '' ]}, {}, class:'char_select' %>
      <span><%= link_to 'Add', new_room_participant_path(@room) %></span></aside>
    <%= f.text_area :content, class:'message_content', disabled: @participants.any? ? false : true %>
<% end %>

app/views/messages/_message_form_user.html.erb
<%= form_for [@room, @message], remote: true, html: {id:"new_message_ooc"} do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
    <%= f.hidden_field :speaker_type, :value => 'User' %>
    <aside class="OOC_contain"><%= render current_user %></aside>
    <%= f.text_area :content, class:'message_content' %>
<% end %>

app/views/messages/create.js.erb
$('#<%= @clear %> .message_content').val('');
console.log('<%= @speaker %>')
$('#messages').append("<%= escape_javascript(raw render(@messages))%>");
scrollBottom();

app/views/messages/index.js.erb
$('#messages').append("<%= escape_javascript(raw render(@messages))%>");
scrollBottom();