config/routes.rb
Rails.application.routes.draw do

  post 'search' => 'pages#search'

  root 'pages#home'

  get 'messages.js' => 'messages#index'

  get 'signup' => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users do
    resources :characters
  end

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :universes do
    resources :groups do
      resources :rooms
    end
  end

  resources :rooms do
    resources :messages, only: [:create]
    resources :participants
  end

  resources :tags, only: [:index, :show]

end

app/models/character.rb
class Character < ActiveRecord::Base
  belongs_to :user
  belongs_to :universe
  has_many :messages, as: :speaker
  has_many :participants
  has_many :rooms, through: :participants
  has_many :char_pictures

  has_attached_file :avatar, styles: {full:"100x100#", thumb:"50x50#", icon:"25x25#"}, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController

  def index
    @user = User.find_by_name(params[:user_id])
    @characters = @user.characters.paginate(page: params[:page], per_page: 10)
  end

  def show
    @character = Character.find_by_id(params[:id])
  end

  def new
    @character = current_user.characters.build
  end

  def create
    @character = current_user.characters.build(character_params)
    if @character.save
      redirect_to [current_user, @character]
    else
      flash[:danger] = "Error creating character"
      redirect_to :back
    end
  end

  def edit
    @character = Character.find_by_id(params[:id])
  end

  def update
    @character = Character.find_by_id(params[:id])
    if @character.update_attributes(character_params)
      flash[:success] = "Character Updated"
      redirect_to [@character.user, @character]
    else
      render 'edit'
    end
  end

  private

    def character_params
      params.require(:character).permit(:name, :avatar)
    end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_character.html.erb
<div class="speaker_display">
  <% if character.avatar.present? %>
    <%= link_to image_tag(character.avatar.url(:icon)), [character.user, character] %>
  <% else %>
    <%= link_to character.name, [character.user, character] %>
  <% end %>
</div>

app/views/characters/edit.html.erb
<% provide(:title, 'Edit Character') %>
<div id="character_form">
  <h1>Edit Character</h1>
  <div>
    <%= form_for [@character.user, @character] do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.text_field :name, placeholder: 'Character Name' %>

        <%= f.label :avatar %>
        <%= f.file_field :avatar %>

        <%= f.submit "Edit Character" %>
    <% end %>
  </div>
</div>

app/views/characters/index.html.erb
<% provide(:title, 'My Characters') %>
<h1>My Characters</h1>
<%= link_to "New Character", new_user_character_path %>
<%= will_paginate %>

<ul class="characters">
  <%= render @characters %>
</ul>

app/views/characters/new.html.erb
<% provide(:title, 'Create New Character') %>
<div id="character_form">
  <h1>New Character</h1>
  <div>
    <%= form_for [@character.user, @character] do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.text_field :name, placeholder: 'Character Name' %>

        <%= f.submit "Create Character" %>
    <% end %>
  </div>
</div>

app/views/characters/show.html.erb
<% provide(:title, @character.name) %>
<div class="row">
    <section class="user_info">
      <h1>
        <%= @character.name %>
      </h1>
      <%= image_tag(@character.avatar.url(:full)) %>
      <% if @character.user == current_user %>
        <%= link_to "Edit", edit_user_character_path %>
      <% end %>
    </section>
</div>