config/routes.rb
Rails.application.routes.draw do

  post 'search' => 'pages#search'

  root 'pages#home'

  get 'messages.js' => 'messages#index'

  get 'signup' => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users do
    resources :characters
  end

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :universes do
    resources :groups do
      resources :rooms
    end
  end

  resources :rooms do
    resources :messages, only: [:create]
    resources :participants
  end

  resources :tags, only: [:index, :show]

end

app/models/room.rb
class Room < ActiveRecord::Base
  belongs_to :group
  has_many :messages
  has_many :participants
  has_many :characters, through: :participants

  acts_as_taggable

  validates :name,  presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false, scope: :group_id }
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def new
    @universe = Universe.find_by_id(params[:universe_id])
    @group = @universe.groups.find_by_id(params[:group_id])
    @room = @group.rooms.build
  end

  def create
    @universe = Universe.find_by_id(params[:universe_id])
    @group = @universe.groups.find_by_id(params[:group_id])
    @room = @group.rooms.build(room_params)
    if @room.save
      redirect_to @room
    else
      flash[:danger] = "group creation failed"
      render 'new'
    end
  end

  def edit
    @room = Room.find_by_id(params[:id])
  end

  def update
    @room = Room.find_by_id(params[:id])
    if @room.update_attributes(room_params)
      redirect_to @room
    else
      flash[:danger] = "unable to save changes"
      redirect_to :back
    end
  end

  def destroy
  end

  def show
    @room = Room.find_by_id(params[:id])
    if @room.nil?
      flash[:danger] = "No such room exists"
      redirect_to rooms_path
    end
    @messages = @room.messages
    @message = @room.messages.build
    @users = @room.group.users
    @participants = @room.characters.where(participants: {approved: 1})
    @requests = @room.characters.where(participants: {approved: 0})
  end

  def index
    @universes = Universe.all
    #@rooms = Room.paginate(page: params[:page], per_page: 10)
  end

  private
    def room_params
      params.require(:room).permit(:name, :private, :closed_canon, :approval_only, :tag_list)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def isPrivateRoom?(room)
    !isMember?(room.group) and room.private?
  end
end

app/views/rooms/_private.html.erb
no can do seniorita

app/views/rooms/_room.html.erb
<li><%= link_to room.name, room %></li>

app/views/rooms/edit.html.erb
<% provide(:title, 'Edit Room') %>
<div id="frontgate">
  <h1>Edit Room for <%= @room.group.name %></h1>
  <div>
    <%= form_for [@room] do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.text_field :name, placeholder: 'Room Name' %>

        <%= f.text_field :tag_list %>

        <%= f.check_box :private %><%= f.label :private %>
        <%= f.check_box :closed_canon %><%= f.label :closed_canon %>
        <%= f.check_box :approval_only %><%= f.label :approval_only %>

        <%= f.submit "Create Room" %>
    <% end %>
  </div>
</div>

app/views/rooms/index.html.erb
<%= link_to "New Room", new_universe_group_room_path(@universe, @group) %>
<ul class="rooms">
  <%= render @rooms %>
</ul>

app/views/rooms/new.html.erb
<% provide(:title, 'New Room') %>
<div id="frontgate">
  <h1>New Room for <%= @group.name %></h1>
  <div>
    <%= form_for [@universe, @group, @room] do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.text_field :name, placeholder: 'Room Name' %>

        <%= f.text_field :tag_list %>

        <%= f.check_box :private %><%= f.label :private %>
        <%= f.check_box :closed_canon %><%= f.label :closed_canon %>
        <%= f.check_box :approval_only %><%= f.label :approval_only %>

        <%= f.submit "Create Room" %>
    <% end %>
  </div>
</div>

app/views/rooms/show.html.erb
<span><%= link_to "All Rooms", root_url %> &gt; <%= link_to @room.group.universe.name, @room.group.universe %> &gt; <%= link_to @room.group.name, [@room.group.universe, @room.group] %></span>
<% if isPrivateRoom?(@room) %>
    <%= render 'private' %>
<% else %>
  <div id="room" data-id="<%= @room.id %>">
    <section id="messages">
      <%= render @messages %>
    </section>
    <aside id="participants">
      <% if isAdminMember?(@room.group) %>
          <%= link_to "Edit Room", edit_room_path %>
          <% @requests.each do |r| %>
              <span><%= render r %><%= link_to "Approve", edit_room_participant_path(@room, r) %></span>
          <% end %>
      <% end %>
      <% @participants.group_by(&:user).each do |user, parts| %>
          <%= render user %><br />
          <% parts.each do |part| %>
            <%= render part %>
          <% end %>
      <% end %>
      <%= render @room.tags %>
    </aside>
    <section id="input">
      <%= render 'messages/message_form_character' %>
      <%= render 'messages/message_form_user' %>
    </section>
  </div>
<% end %>